version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    resource_class: small

    steps:
      - checkout

      - run:
          name: Install system packages
          command: |
            sudo apt-get update
            sudo apt-get install -y default-jre-headless

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run tests
          command: |
            pipenv run python -m unittest discover tests